
- name: Ensure Red Hat Quay Operator Subscription is installed
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-operator_subscription.j2') }}"
  delegate_to: localhost

- name: Ensure installPlanApproval is set to Manual
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-operator_subscription.j2') }}"
  delegate_to: localhost
  vars:
    installPlanApproval: Manual

- name: Create {{ quay_install_openshift_role_namespace }} namespace
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-registry_namespace.j2') }}"
  delegate_to: localhost

- name: Create config bundle Secret
  community.kubernetes.k8s:
    state: present
    kind: Secret
    name: "{{ quay_install_openshift_role_configBundleSecret_name }}"
    namespace: "{{ quay_install_openshift_role_namespace }}"
    definition: "{{ lookup('template', 'config-bundle_secret.j2') }}"
  delegate_to: localhost
  when: quay_install_openshift_role_cr_configBundleSecret

- name: Create QuayRegistry instance
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quayregistries.quay.redhat.com.j2') }}"
  delegate_to: localhost

