
- name: Create {{ quay_install_openshift_role_namespace }} namespace
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-registry_namespace.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost

- name: Ensure Red Hat Quay Operator Subscription is installed
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-operator_subscription.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost

- name: Ensure installPlanApproval is set to Manual
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-operator_subscription.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost
  vars:
    installPlanApproval: Manual

- name: Create operatorgroup if quay operator is installed into specific namespace
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-operatorgroup_namespaced.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost
  when: not quay_install_openshift_role_operator_all_namespaces

- name: Create config bundle Secret
  community.kubernetes.k8s:
    state: present
    kind: Secret
    name: "{{ quay_install_openshift_role_configBundleSecret_name }}"
    namespace: "{{ quay_install_openshift_role_namespace }}"
    definition: "{{ lookup('template', 'config-bundle_secret.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost
  when: quay_install_openshift_role_cr_configBundleSecret

- name: Create QuayRegistry instance
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quayregistries.quay.redhat.com.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost

- name: Create custom Quay's App Route using SERVER_HOSTNAME variable
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-app_route.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost
  when:
    - quay_install_openshift_role_server_hostname is defined
    - not quay_install_openshift_role_cr_route

- name: Create Quay's Config Editor Route when route component is unmanaged
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'quay-config-editor_route.j2') }}"
    validate_certs: "{{ quay_install_openshift_role_validate_certs | default(True) }}"
  delegate_to: localhost
  when: not quay_install_openshift_role_cr_route
